;;; -*- Mode:Common-Lisp; Package:USER; Base:10; Fonts:(MEDFNT MEDFNB HL12BI) -*-

;1                           RESTRICTED RIGHTS LEGEND*

;1Use, duplication, or disclosure by the Government is subject to*
;1restrictions as set forth in subdivision (b)(3)(ii) of the Rights in*
;1Technical Data and Computer Software clause at 52.227-7013.*
;
;1                     TEXAS INSTRUMENTS INCORPORATED.*
;1                              P.O. BOX 2909*
;1                           AUSTIN, TEXAS 78769*
;
;1 Copyright (C) 1985, 1988 Texas Instruments Incorporated. All rights reserved.*
;1;*
;1;                SYSTEM DEFINITIONS for IP*
;1;*
(defpackage ip)

(defsystem ip
  (:name "IP")
  (:short-name "IP")  
  (:pathname-default "IP:IP;")
  (:patchable "IP:IP-PATCH;" patch)
  (:warnings-pathname-default "ip:cwarns;ip.lisp")
  (:module defs     "IP-DEFS")
  (:module non-arp  "IP-Non-ARP")
  (:module route    "IP-ROUTING")
  (:module setup    "Setup-my-address")
  (:module main     "IP")
  (:module icmp     "ICMP")
  (:module host-status "HOST-STATUS")
  (:module udpdefs  "UDPDEFS")
  (:module udp      "UDP")
  (:module udphand  "UDPHAND")
  (:module udp-peek "UDP-PEEK")
  (:module udp-protocols "UDP-PROTOCOLS")
  (:module udp-stream "udp-stream")
  (:module test     "TEST-PKT")
  (:module reset    "reset")
  (:module tdef     "TFTP-DEFS")
  (:module tfnm     "TFTP-F-N-M")
  (:module tmain    "TFTP-MAIN")
  (:module ftpint     "ftpint"  )
  (:module ftp-str    "ftp-stream")
  (:module tcp-str    "tcp-stream")
  (:module ftp-peek   "ftp-peek"  )
  (:module ip-access  "ip-access")
  (:module tcpdefs    "TCPDEFS")
  (:module tcp        "TCP")
  (:module tcpconn    "TCPCONN")
  (:module tcphand    "TCPHAND")
  (:module tcp-peek   "TCP-PEEK")
  (:module tcp-protocols "TCP-PROTOCOLS")
  (:module tcp-medium "TCP-MEDIUM")
  (:module udp-medium "UDP-MEDIUM")
  (:module peekn      "peekn")
  (:module ftp        "ftp")
  (:module ftp-server "ftp-server")
  (:module ip-address "ip-address")
  (:module ftp-window "ftpi")	
  (:module telnet-server "telnet-server")
  (:module telnet-stream "telnet-stream")
  (:module ip-debug   "IP-DEBUG")
  (:module icmp-peek  "ICMP-PEEK")
  (:module mail       "ip-smtp")
  (:module arp        "IP-ARP")
  (:module auxiliary  "SYS:SITE;IP.SYSTEM")

  (:compile-load defs)
  (:compile-load arp)
  (:compile-load non-arp    (:fasload defs) (:fasload defs))
  (:compile-load setup)
  (:compile-load route      (:fasload defs arp setup) (:fasload defs arp setup))
  (:compile-load icmp       (:fasload defs route) (:fasload defs route))
  (:compile-load host-status (:fasload icmp) (:fasload icmp))
  (:compile-load main       (:fasload defs non-arp arp route icmp setup)
		            (:fasload defs non-arp arp route icmp setup))
  (:compile-load ip-debug   (:fasload defs icmp) (:fasload defs icmp))  
  (:compile-load test       (:fasload defs) (:fasload defs))
  (:compile-load reset)
  (:compile-load ip-access)
  (:compile-load ip-address)
  (:compile-load tcpdefs (:fasload defs) (:fasload defs))
  (:compile-load-init tcphand (tcpdefs) (:fasload tcpdefs) (:fasload tcpdefs))
  (:compile-load-init tcp    (tcpdefs) (:fasload tcpdefs tcphand) (:fasload tcpdefs tcphand))
  (:compile-load-init tcpconn (tcpdefs) (:fasload tcpdefs tcphand) (:fasload tcpdefs tcphand))
  (:compile-load-init tcp-protocols (tcpdefs) (:fasload tcpdefs tcp tcphand) (:fasload tcpdefs tcp tcphand))
  (:compile-load-init tcp-str      (tcpdefs) (:fasload tcpdefs tcphand) (:fasload tcpdefs tcphand))
  (:compile-load-init tcp-peek   (tcpdefs) (:fasload tcpdefs tcphand) (:fasload tcpdefs tcphand))
  (:compile-load tcp-medium (:fasload tcp-str) (:fasload tcp-str))
  (:compile-load udpdefs (:fasload defs setup main route tcp) (:fasload defs setup main route tcp))
  (:compile-load-init udphand  (udpdefs) (:fasload udpdefs) (:fasload udpdefs))
  (:compile-load-init udp (udpdefs) (:fasload udphand) (:fasload udphand))
  (:compile-load-init udp-protocols (udpdefs) (:fasload udp udphand tcp-protocols)
		      (:fasload udp udphand tcp-protocols))
  (:compile-load-init udp-peek  (udpdefs)  (:fasload udp udphand) (:fasload udp udphand))
  (:compile-load-init udp-medium (udpdefs tcp-medium) (:fasload udp) (:fasload udp tcp-medium))
  (:compile-load udp-stream (:fasload tcp-str) (:fasload tcp-str))
  (:compile-load telnet-stream (:fasload tcp-str) (:fasload tcp-str))
  (:compile-load ftp        (:fasload defs main route tcp-str telnet-stream)
		            (:fasload defs main route tcp-str telnet-stream))
  (:compile-load ftp-server (:fasload defs main route tcp-str ftp telnet-stream)
		            (:fasload defs main route tcp-str ftp telnet-stream))
  (:compile-load ftp-peek (:fasload ftp) (:fasload ftp))
  (:compile-load ftpint     (:fasload  ftp ftp-peek) (:fasload ftp ftp-peek))
  (:compile-load ftp-str (:fasload ftp ftpint) (:fasload ftp ftpint))
  (:compile-load ftp-window (:fasload ftp) (:fasload ftp))
  (:compile-load tdef)
  (:compile-load tmain      (:fasload tdef udp ip-access) (:fasload tdef udp ip-access))
  (:compile-load tfnm       (:fasload tdef tmain udp ip-access) (:fasload tdef tmain udp ip-access))
  (:compile-load icmp-peek  (:fasload icmp) (:fasload icmp))
  (:compile-load peekn     (:fasload tcp tcp-peek) (:fasload tcp tcp-peek))
  (:compile-load ip-debug   (:fasload defs icmp) (:fasload defs icmp))
  (:auxiliary auxiliary)
  )

